production:
  primary:
    adapter: postgresql
    encoding: utf8
    database: postgres
    pool: 5
    username: postgres
    password: password
    host:  host.docker.internal # This should match the service name defined in your docker-compose.yml

  queue:
    adapter: postgresql
    encoding: utf8
    database: postgres
    pool: 5
    username: postgres
    password: password
    host:  host.docker.internal
   # This should match the service name defined in your docker-compose.yml

  cache:
    adapter: postgresql
    encoding: utf8
    database: postgres
    pool: 5
    username: postgres
    password: password
    host:  host.docker.internal
development:
  primary:
    adapter: postgresql
    encoding: utf8
    database: postgres
    pool: 5
    username: postgres
    password: password
    host:  host.docker.internal # This should match the service name defined in your docker-compose.yml

  queue:
    adapter: postgresql
    encoding: utf8
    database: postgres
    pool: 5
    username: postgres
    password: password
    host:  host.docker.internal
    # This should match the service name defined in your docker-compose.yml

  cache:
    adapter: postgresql
    encoding: utf8
    database: postgres
    pool: 5
    username: postgres
    password: password
    host:  host.docker.internal
